# Generated by Django 2.0.7 on 2018-08-01 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deputy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('workplace', models.CharField(default=None, max_length=200)),
                ('declaration_id', models.CharField(blank=True, default=None, max_length=200)),
                ('incomes', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='deputy',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Declarations.PoliticalParty'),
        ),
    ]
